### ISSUE TITLE
`in_threaded_loop not defined`

### ISSUE THREAD

**Issue by grahamas** [Jutho/Strided.jl#6]
On julia nightly (8 days old) when julia is run with `JULIA_NUM_THREADS=N` for `N > 1` and code inside `@distributed`.   Stack trace leads to `mapreduce.jl:130`. 

For various reasons my code doesn't work on previous julia versions, but I'll update here as I'm able to isolate the error.  Any advice appreciated.

**Comment by Jutho** [comment]
I use some unexported, i.e. private properties of the `Base.Threads`, which has probably changed with the new threading infrastructure of Julia 1.3. I'll take a look into this.

**Comment by Jutho** [comment]
fixed on master, I will tag a new version.
